apiVersion: apps/v1
kind: Deployment
metadata:
  name: deply-jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
              fsGroup: 1000
              runAsUser: 0
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: hyunkyoungkang/jenkins-docker-gradle:latest
          securityContext:
              privileged: true
          ports:
            -  containerPort: 8080
            -  containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: docker-data
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-data
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000

